version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    
    # please read https://github.com/hlf20010508/telegram-onedrive#preparation before editing

    ports:
      - 8080:8080

    volumes:
      - telegram-onedrive-session:/telegram-onedrive/session
      # if you have your own ssl files, uncomment and edit these two lines:
      # - /path/to/*.crt:/telegram-onedrive/server/ssl/server.crt
      # - /path/to/*.key:/telegram-onedrive/server/ssl/server.key

    environment:
      - server_uri=https://127.0.0.1:8080
      - reverse_proxy=false
      - tg_bot_token=7443034654:AAH83ai22x0R_um_D4zHToFIiCAv8M1q4Co
      - tg_api_id=23940130
      - tg_api_hash=4d717a6f888e37b7ebde0ace80cd22c6
      - tg_user_phone=+918013080180
      # - tg_user_password=xxxxxxxx
      # - tg_user_name=xxxxxxxx
      - od_client_id=361f37ea-ef1e-4062-9bee-0bc1ee598b69
      - od_client_secret=fd68Q~OWFBdq3pxnhae4hesYSk4QAnoJS7nTUa_v
      - remote_root_path=/xxxxxxxx
      - delete_flag=false
    command: python main.py

volumes:
  telegram-onedrive-session:
